---
services: docker

env:
  - distro: debian8
    playbook: test.yml
  - distro: debian9
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: ubuntu1404
    playbook: test.yml
  - distro: fedora24
    playbook: test.yml

script:
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download geerlingguy's test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
